config/routes.rb
Rails.application.routes.draw do

  root to: 'videos#index'

  post 'sessions/create'
  get 'sessions/remove'
  get 'sessions/error'

  resources :videos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:access_token] = Zype.new.get_access_token(params[:session][:email], params[:session][:password])

    if session[:access_token]
      redirect_to video_path(params[:session][:id])
    else
      redirect_to sessions_error_path
    end
  end

  def remove
    if session[:access_token]
      session[:access_token] = nil
    end
    redirect_to videos_path
  end

  def error
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def index
    @videos = Zype.new.get_videos
  end

  def show
    @video = Zype.new.get_video(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZypeAPI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/videos/_not_subscription.html.erb
<div>
  <div class="alert alert-success " role="alert">
    <div class="d-inline p-2">This video does not need subscription to reproduce</div>
    <div class="d-inline p-2">
      <a href="<%=videos_path%>" class="p-2 bg-info text-white">go back</a>
    </div>
  </div>
  
  <div id="zype_<%=params[:id]%>"></div>

  <script src="https://player.zype.com/embed/<%=params[:id]%>.js?autoplay=true&app_key=XWny5j0V89yb1uZu6SI_D95EADV5FzBYldE9Ny0_q0GOzcWLiruPyhN-f2Pcyohf" type="text/javascript"></script>
</div>

app/views/videos/_subscription.html.erb
<% if session[:access_token] %>

  <div>
    <div class="alert alert-success " role="alert">
      <div class="d-inline p-2">You are subscribed</div>
      <div class="d-inline p-2">
        <a href="<%=videos_path%>" class="p-2 bg-info text-white">Video List</a>
      </div>
      <div class="d-inline p-2">
        <a href="<%=sessions_remove_path%>" class="p-2 bg-danger text-white">Unsubscribe</a>
      </div>
    </div>

    <div id="zype_<%=params[:id]%>"></div>

    <script src="https://player.zype.com/embed/<%=params[:id]%>.js?autoplay=true&access_token=<%=session[:access_token]%>" type="text/javascript"></script>
  </div>

<% else %>

  <div class="row ">
    <div class="col-sm-3"></div>
    <div class="col-sm-6">
      <h1 class="text-center login-title">Subscribe</h1>
      <div class="account-wall">
        <%= form_for(:session, url: sessions_create_path) do |f| %>

          <div class="form-group">
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>

          <div class="form-group">
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>

          <%= f.hidden_field :id, value: params[:id]%>

          <%= f.submit "Log in", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-3"></div>
  </div>

<% end %>

app/views/videos/index.html.erb
<div class="row">
  <ul class="listrap">
    <% @videos.each_with_index do |video, index| %>
      <li>
        <a href="<%=video_path(video['_id'])%>">
          <div class="listrap-toggle">
            <span></span>
            <%= image_tag(video["thumbnails"][0]["url"], class: "gallery__img") %>
          </div>
          <strong><%= video["title"] %></strong>
        </a>
      </li>
    <% end %>
  </ul>
</div>

app/views/videos/show.html.erb
<% if @video["subscription_required"] && session %>
  <%= render "subscription" %>
<% else %>
  <%= render "not_subscription" %>
<% end %>